### ISSUE TITLE
belg

### ISSUE THREAD

**Issue by marcosci** [r-spatialecology/landscapeverse#1]
@Nowosad , did you on purpose not include belg in the installation script and only in the README? :)

**Comment by Nowosad** [comment]
Hm.. I've added it to DESCRIPTION (https://github.com/r-spatialecology/landscapeverse/blob/master/DESCRIPTION), so it should be installed with **landscapeverse**. 
It is not going to attach this package though (on purpose).

Am I missing something?

**Comment by marcosci** [comment]
Ah, ok - now, that's fine. I thought you wanted to load it somehow :)
